### ISSUE TITLE
Orthogonal factors

### ISSUE THREAD

**Issue by ngjuping** [UePG-21/gpquant#5]
Hello, may I please ask how to generate multiple orthogonal factors that tries to fit y with X? It seems that the current implementation only supports fitting one expression for one y, so some manual decomposition of Y is required. If you are too busy to implement, please share how would you try to tackle this. Here is my thought:

Implement another fitness eval function, that is sharpe - sum(correlation(prev_results))

Hope to hear from you soon, nice work!

Best regards,
JU PING

**Comment by ngjuping** [comment]
Preferably, multiple factor for one time series. I'm interested to use this to model some future contract's returns.

**Comment by UePG-21** [comment]
Thanks for reaching out. Firstly, I agree with your solution. Also, I may try to fit one best factor then decompose it to multiple factors according to a pre-specified linear relationship. You can try both by yourself.

**Comment by ngjuping** [comment]
Can you elaborate on the second solution? An example would be the best!

**Comment by UePG-21** [comment]
I'm busy on another project, but here's one possible solution I came up to mind without tailoring the fitness:

Since the expression of the factor you mine is explicit, you can approximate it by a Taylor series (auto-grad in PyTorch may be helpful) where each component is correlated but not too much. Then you apply PCA on those component to get orthogonal factors.

Feel free to connect me on WeChat 15046104088 for further discussion.

**Comment by ngjuping** [comment]
I will try it out, thanks
